version: '3.8'
services:
  app:
    image: 'ghcr.io/ingenjorsarbete-for-klimatet/infrastructure/oauth:latest'
    restart: unless-stopped
    ports:
      - '3000:80'
    environment:
      OAUTH_CLIENT_ID: /run/secrets/client_id
      OAUTH_CLIENT_SECRET: /run/secrets/client_secret
    secrets:
      - client_id
      - client_secret
secrets:
  client_id:
    file: ./secrets/client_id
  client_secret:
    file: ./secrets/client_secret