version: '3.8'
services:
  app:
    image: 'ghcr.io/ingenjorsarbete-for-klimatet/infrastructure/oauth:latest'
    restart: unless-stopped
    ports:
      - '3000:80'
    environment:
      OAUTH_CLIENT_ID: ${CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${CLIENT_SECRET}
      PORT: 80
      ORIGINS: ingenjorsarbeteforklimatet.se